from __future__ import annotations

from pydantic import BaseModel, Field
from typing import Literal, List
from datetime import datetime
import uuid


Severity = Literal["LOW", "MEDIUM", "HIGH"]


class Insight(BaseModel):
    """
    Insight generated by the backend intelligence engine.

    This is intentionally "explainable AI": it provides drivers + a recommended action.
    """
    id: str = Field(default_factory=lambda: f"ins_{uuid.uuid4().hex[:10]}")
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat() + "Z")
    scenario: str

    severity: Severity
    category: str

    message: str
    drivers: List[str] = Field(default_factory=list)
    recommendation: str
    confidence: int = 70  # 0-100
